spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  datasource:
    url: jdbc:mysql://db:3306/hearthstone_db
    username: root
    password: deckgen

server:
  servlet:
    contextPath: /deckgenerator


blizzard:
  api:
    encoding: UTF-8
    token-url: https://us.battle.net/oauth/token?grant_type=client_credentials
    hearthstone-base-url: https://us.api.blizzard.com/hearthstone
    locale: en_US

