spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 500
          order_inserts: true

  datasource:
    url: jdbc:postgresql://localhost:5432/hearthstone_db
    reWriteBatchedInserts: true
    cachePrepStmts: true
    useServerPrepStmts: true
    username: root
    password: deckgen

server:
  servlet:
    contextPath: /deckgenerator
  port: 8080


blizzard:
  api:
    encoding: UTF-8
    token-url: https://us.battle.net/oauth/token?grant_type=client_credentials
    hearthstone-base-url: https://us.api.blizzard.com/hearthstone
    locale: en_US
    page-size: 500

